name: Checks

on:
  push:
    branches: ['**']
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: leafo/gh-actions-lua@v13
        with:
          luaVersion: "5.1.5"
      - uses: leafo/gh-actions-luarocks@v6
      - run: luarocks install luacheck
      - run: tools/check.sh
